import React from 'react';
import { Link } from 'react-router-dom';
import LegalLayout from '@/components/layout/LegalLayout';
import { PageHero, Prose, Section, Sub, P, UL, Callout, Divider } from '@/components/legal/LegalKit';

const LAST_UPDATED = 'October 3, 2026';

export default function PrivacyPolicy() {
  return (
    <LegalLayout
      title="Lumos Logic HRMS Privacy Policy"
      description="Privacy Policy for Lumos Logic HRMS — how employee, attendance, leave, payroll and other HR data is collected, used, stored and protected."
      path="/privacy-policy"
    >
      <PageHero
        eyebrow="Legal"
        title="Privacy Policy"
        subtitle="How Lumos Logic HRMS handles the personal information processed on behalf of your organization."
        meta={[`Effective Date: ${LAST_UPDATED}`, `Last Updated: ${LAST_UPDATED}`]}
      />

      <Prose>
        <P>
          This Privacy Policy explains how <strong>Lumos Logic</strong> (&ldquo;Lumos Logic&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo; or &ldquo;our&rdquo;)
          collects, uses, stores and shares personal information through <strong>Lumos Logic HRMS</strong> (&ldquo;HRMS&rdquo; or the &ldquo;Service&rdquo;),
          a human resource management platform that provides attendance, leave, payroll, document, expense and performance management
          for organizations and their employees.
        </P>

        <Section id="who-applies" title="1. Who This Policy Applies To">
          <P>This Policy applies to:</P>
          <UL items={[
            <><strong>Organizations / employers</strong> — companies that register and use Lumos Logic HRMS to manage their workforce.</>,
            <><strong>Administrators</strong> — HR administrators and root administrators who configure and operate the Service on behalf of an organization.</>,
            <><strong>Employees / end users</strong> — individuals whose HR records are stored in the Service and who access it through the employee portal or mobile application.</>,
          ]} />
          <P>
            <strong>Important:</strong> When you use Lumos Logic HRMS, your employer (the organization) is generally the party that decides
            what employee information is entered into the Service and how it is used. Lumos Logic processes that information as a service provider
            on the organization&rsquo;s behalf. For questions about how your employer uses your information, please contact your organization&rsquo;s HR team.
          </P>
        </Section>

        <Section id="information-we-process" title="2. Personal Information We Process">
          <P>
            We process personal information that is provided to the Service by organizations, administrators and employees, or that is
            generated by use of the Service. This may include:
          </P>
          <Sub title="Account &amp; Authentication Information">
            <UL items={[
              <>Name, work email address, and a securely hashed password.</>,
              <>Role (employee, HR admin, root admin), department and position/title.</>,
              <>Optional two-factor authentication (2FA) configuration where enabled.</>,
            ]} />
          </Sub>
          <Sub title="Employee Profile Information">
            <UL items={[
              <>Personal details such as full name, salutation, date of birth, gender, blood group, marital status, nationality, and profile photo (where provided).</>,
              <>Contact details such as phone number, personal email address, and residential/permanent address.</>,
              <>Family, emergency contact, education, work experience, skills, nominee and training/certification details where entered by the organization or employee.</>,
            ]} />
          </Sub>
          <Sub title="Employment / Job Information">
            <UL items={[
              <>Employee code, joining date, employment type, work mode, designation, department, branch and reporting structure.</>,
              <>Compensation and statutory details such as salary structure, bank account details, PAN, UAN/PF number and other government identifiers where configured.</>,
            ]} />
          </Sub>
          <Sub title="Attendance Information">
            <UL items={[
              <>Clock-in and clock-out times, break times, work hours, late/early-exit flags and daily status (present, absent, half day, WFH, on leave).</>,
              <>Biometric punch records where an organization connects ZKTeco biometric devices.</>,
            ]} />
          </Sub>
          <Sub title="Leave Information">
            <UL items={[
              <>Leave requests including leave type, date range, duration, reason/remarks, status and approver details.</>,
              <>Leave balances and policy quotas.</>,
            ]} />
          </Sub>
          <Sub title="Payroll / Payslip Information">
            <UL items={[
              <>Salary structure, deductions, tax-related fields and generated payslips.</>,
              <>Banking and statutory identifiers used for payroll processing.</>,
            ]} />
          </Sub>
          <Sub title="Documents Uploaded to HRMS">
            <UL items={[
              <>Documents uploaded by employees or administrators, such as identity documents (Aadhaar, PAN), bank proofs, educational and employment records.</>,
            ]} />
          </Sub>
          <Sub title="Expense Information">
            <UL items={[
              <>Expense claims including title, category, amount, expense date, description and uploaded receipts.</>,
            ]} />
          </Sub>
          <Sub title="Performance-Related Information">
            <UL items={[
              <>Goals, OKRs, review ratings, self and manager comments where performance modules are used.</>,
            ]} />
          </Sub>
          <Sub title="Notifications &amp; Device Information">
            <UL items={[
              <>In-app notification records and, where an organization uses push notifications, web or mobile push subscription tokens.</>,
              <>For the mobile application, a device token plus basic device metadata (platform, device name and model) when the user enables push notifications.</>,
            ]} />
          </Sub>
          <Sub title="Technical / Log Information">
            <UL items={[
              <>IP address and browser/device user-agent recorded for sign-in and certain requests, and rate-limiting/security purposes.</>,
              <>Server-side logs used for security, troubleshooting and service improvement.</>,
            ]} />
          </Sub>
          <Callout title="What Lumos Logic HRMS does not collect">
            <P>
              The HRMS does not use advertising identifiers, does not track you across third-party websites or apps, and does not sell
              personal information. We do not process precise location data for attendance; attendance is time-based (or device-based where
              biometric hardware is connected).
            </P>
          </Callout>
        </Section>

        <Section id="sources" title="3. Sources of Personal Information">
          <UL items={[
            <><strong>Provided by organizations / employers</strong> — employee records, job details, compensation and documents entered by administrators.</>,
            <><strong>Provided directly by users</strong> — profile edits, leave requests, expense claims, document uploads and regularization requests submitted by employees.</>,
            <><strong>Generated through use</strong> — attendance punches, notifications and technical/log data.</>,
          ]} />
        </Section>

        <Section id="purposes" title="4. How We Use Personal Information">
          <UL items={[
            <>Authentication and access control, including verifying identity and managing sessions and 2FA.</>,
            <>Employee management — maintaining employee profiles and organizational structure.</>,
            <>Attendance management — recording and reporting attendance and connecting biometric devices.</>,
            <>Leave management — processing leave requests, balances and approvals.</>,
            <>Payroll — generating salary structures and payslips.</>,
            <>Documents — storing, organizing and sharing HR documents.</>,
            <>Expenses — processing expense claims and reimbursements.</>,
            <>Performance — tracking goals and reviews.</>,
            <>Notifications — delivering in-app and push/email notifications.</>,
            <>HR operations — onboarding, exit management and other HR workflows.</>,
            <>Security and troubleshooting — monitoring for misuse, diagnosing issues and enforcing rate limits.</>,
            <>Service improvement — understanding usage to improve reliability and features (in aggregate where possible).</>,
          ]} />
        </Section>

        <Section id="storage-protection" title="5. How Information Is Stored &amp; Protected">
          <UL items={[
            <>Data is stored in a PostgreSQL database with organization-level separation (multi-tenancy).</>,
            <>Uploaded files (documents and receipts) are stored with a third-party cloud storage provider (Cloudinary).</>,
            <>Passwords are stored using one-way hashing (not plain text), and authentication uses signed JSON Web Tokens (JWT).</>,
            <>Access to the Service is role-based; users only see data their role and permissions allow.</>,
            <>Traffic is served over HTTPS, and the API enforces authentication and rate limiting.</>,
          ]} />
          <P>
            No method of transmission or storage is completely secure, and we cannot guarantee absolute security. We take reasonable
            administrative, technical and organizational measures appropriate to the data we process. For more detail, see our
            <Link to="/security" className="text-[#3525cd] font-semibold hover:underline"> Security &amp; Data Protection</Link> page.
          </P>
        </Section>

        <Section id="sharing" title="6. When Information Is Shared">
          <Sub title="With your organization / employer">
            <P>
              Administrators and authorized personnel of the organization that controls your account can access employee information
              managed through the Service (for example, HR administrators and root administrators can view attendance, leave, documents
              and payroll records for their organization).
            </P>
          </Sub>
          <Sub title="With service providers">
            <P>
              We use a limited set of third-party service providers to operate the Service, such as cloud storage for uploaded files
              and an email delivery service. These providers only process information as necessary to provide their services to us.
            </P>
          </Sub>
          <Sub title="For legal or security reasons">
            <P>
              We may disclose information where required by applicable law, regulation, legal process, or to protect the rights, safety
              or security of Lumos Logic, our customers or the public.
            </P>
          </Sub>
          <P>We do not sell personal information.</P>
        </Section>

        <Section id="retention" title="7. Data Retention &amp; Deletion">
          <P>
            Employee information is generally retained for as long as an organization maintains an active relationship with the Service,
            and is controlled primarily by the organization. Some records (for example, payroll and statutory information) may be retained
            for longer where required by applicable legal, tax or regulatory obligations.
          </P>
          <P>
            Requests to delete or deactivate an account are handled as described in our
            <Link to="/account-deletion" className="text-[#3525cd] font-semibold hover:underline"> Account &amp; Data Deletion</Link> page.
            Because employee accounts are organization-controlled, deletion requests may need to be coordinated with your employer.
          </P>
        </Section>

        <Section id="rights" title="8. Your Rights &amp; Choices">
          <P>Depending on your location and applicable law, you may have rights to:</P>
          <UL items={[
            <>Access the personal information we hold about you.</>,
            <>Request correction of inaccurate information.</>,
            <>Request deletion of your personal information.</>,
            <>Object to or restrict certain processing.</>,
            <>Withdraw consent where processing is based on consent.</>,
          ]} />
          <P>
            For information held on behalf of your employer, the quickest way to exercise these rights is to contact your organization&rsquo;s
            HR administrator. You may also contact us at the address below, and we will help as appropriate.
          </P>
        </Section>

        <Section id="policy-updates" title="9. Changes to This Policy">
          <P>
            We may update this Privacy Policy from time to time. When we do, we will revise the &ldquo;Last Updated&rdquo; date at the top of this page.
            Material changes will be communicated through the Service or this website as appropriate.
          </P>
        </Section>

        <Section id="contact" title="10. Contact Us">
          <P>
            For privacy questions, data requests or concerns about this Policy, contact us at
            <a href="mailto:hello@lumoslogic.com" className="text-[#3525cd] font-semibold hover:underline"> hello@lumoslogic.com</a> or
            use the <Link to="/contact" className="text-[#3525cd] font-semibold hover:underline">Contact &amp; Support</Link> page.
          </P>
        </Section>

        <Divider />
        <P className="text-sm text-[#777587]">
          Lumos Logic HRMS is a product of Lumos Logic. This Policy describes the Lumos Logic HRMS platform; it does not describe the
          separate privacy practices of any individual organization that uses the Service.
        </P>
      </Prose>
    </LegalLayout>
  );
}
